# -*- coding: utf-8 -*-
"""hf_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UAcB58qGcMO5hJX-Dxz7Gx2kWnlehUJ

# HuggingFace CIFAR-10 Training with ResNet18
## Run on Google Colab with W&B Logging

This notebook trains a pretrained ResNet18 on CIFAR-10 from HuggingFace, logs metrics to W&B, and pushes the best model to HF Hub.
"""

# Cell 1: Install dependencies
!pip install torch torchvision datasets huggingface_hub wandb matplotlib seaborn scikit-learn pandas Pillow -q
print(" All packages installed successfully!")

# Cell 2: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')
print(" Google Drive mounted!")

# Cell 3: W&B and HuggingFace login (run once)
# Uncomment the lines below on first run
!wandb login
!huggingface-cli login

# Cell 4: Import libraries and check GPU
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import transforms, models
from datasets import load_dataset
from PIL import Image
import wandb
from huggingface_hub import upload_folder
import os
import numpy as np

# Check GPU availability
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f" Using device: {DEVICE}")
if torch.cuda.is_available():
    print(f"  GPU: {torch.cuda.get_device_name(0)}")

# Cell 5: Configuration
# ==========================
# Configuration
# ==========================
BATCH_SIZE = 32
NUM_CLASSES = 10
EPOCHS = 10
LR = 1e-3
HF_MODEL_REPO = "https://huggingface.co/datasets/Chiranjeev007/CIFAR-10_Subset"  # Change to your HF username/repo
WANDB_PROJECT = "cifar10-hf"

print(f"Configuration:")
print(f"  Batch Size: {BATCH_SIZE}")
print(f"  Epochs: {EPOCHS}")
print(f"  Learning Rate: {LR}")
print(f"  Device: {DEVICE}")
print(f"  W&B Project: {WANDB_PROJECT}")
print(f"  HF Repo: {HF_MODEL_REPO}")

# Cell 6: Initialize W&B
# ==========================
# W&B Initialization
# ==========================
wandb.init(project=WANDB_PROJECT, name="resnet18-cifar10", config={
    "batch_size": BATCH_SIZE,
    "epochs": EPOCHS,
    "learning_rate": LR,
    "optimizer": "Adam",
    "model": "ResNet18"
})
print(" W&B initialized")

# Cell 7: Load CIFAR-10 dataset from HuggingFace
# ==========================
# Load CIFAR-10 from HuggingFace
# ==========================
print("Loading CIFAR-10 dataset...")
dataset = load_dataset("cifar10")

# Get train split for training
train_data = dataset["train"]
test_data = dataset["test"]

# CIFAR-10 class names
class_names = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck"]

print(f" Dataset loaded!")
print(f"  Train samples: {len(train_data)}")
print(f"  Test samples: {len(test_data)}")
print(f"  Classes: {class_names}")

# Cell 8: Define transforms and custom dataset class
# ==========================
# Transforms
# ==========================
transform_train = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

transform_val = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# ==========================
# Custom Dataset Class
# ==========================
class CIFAR10Dataset(torch.utils.data.Dataset):
    def __init__(self, hf_dataset, transform=None):
        self.dataset = hf_dataset
        self.transform = transform

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        item = self.dataset[idx]
        image = item["img"].convert("RGB")
        label = item["label"]

        if self.transform:
            image = self.transform(image)

        return image, label

print(" Transforms and dataset class defined")

# Cell 9: Create datasets and dataloaders
# Create datasets
train_dataset = CIFAR10Dataset(train_data, transform=transform_train)
val_dataset = CIFAR10Dataset(test_data, transform=transform_val)

# Split train into train/validation (80/20)
train_size = int(0.8 * len(train_dataset))
val_size = len(train_dataset) - train_size
train_dataset, _ = random_split(train_dataset, [train_size, val_size])

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(f" DataLoaders created!")
print(f"  Train batches: {len(train_loader)}")
print(f"  Val batches: {len(val_loader)}")

# Cell 10: Load pretrained ResNet-18 model
# ==========================
# Load Pretrained ResNet-18
# ==========================
print("Loading pretrained ResNet-18...")
model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
model.fc = nn.Linear(model.fc.in_features, NUM_CLASSES)
model = model.to(DEVICE)

# Count parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f" Model loaded!")
print(f"  Total parameters: {total_params:,}")
print(f"  Trainable parameters: {trainable_params:,}")

# Cell 11: Setup loss function and optimizer
# ==========================
# Loss & Optimizer
# ==========================
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=LR)

print(f" Loss function: CrossEntropyLoss")
print(f" Optimizer: Adam (lr={LR})")

# Cell 12: Training loop
# ==========================
# Training Loop
# ==========================
best_val_loss = float('inf')
best_model_state = None

print("Starting training...")
print("=" * 70)

for epoch in range(EPOCHS):
    # Training
    model.train()
    train_loss = 0.0
    train_correct = 0
    train_total = 0

    for batch_idx, (images, labels) in enumerate(train_loader):
        images = images.to(DEVICE)
        labels = labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        train_total += labels.size(0)
        train_correct += (predicted == labels).sum().item()

    train_loss /= len(train_loader)
    train_acc = 100 * train_correct / train_total

    # Validation
    model.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            outputs = model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    val_loss /= len(val_loader)
    val_acc = 100 * val_correct / val_total

    print(f"Epoch [{epoch+1:2d}/{EPOCHS}] Train Loss: {train_loss:.4f} Train Acc: {train_acc:6.2f}% | "
          f"Val Loss: {val_loss:.4f} Val Acc: {val_acc:6.2f}%")

    # Log to W&B
    wandb.log({
        "train_loss": train_loss,
        "train_accuracy": train_acc,
        "val_loss": val_loss,
        "val_accuracy": val_acc,
        "epoch": epoch + 1
    })

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_model_state = model.state_dict()
        print(f" Best model saved (val_loss: {best_val_loss:.4f})")

print("=" * 70)
print(" Training Complete!")

# Cell 13: Save model and push to HuggingFace Hub
# ==========================
# Save & Push Model to HuggingFace Hub
# ==========================

if best_model_state:
    torch.save(best_model_state, "best_model.pt")
    print(" Model saved locally as best_model.pt")

    # Push to HF Hub (requires HF login)
    try:
        print(f"\n Pushing model to HuggingFace Hub at {HF_MODEL_REPO}...")
        # Create a simple config file for the model
        config_text = f"""---
license: apache-2.0
---
# CIFAR-10 ResNet18 Model

Pretrained ResNet18 fine-tuned on CIFAR-10 dataset.

## Model Details
- **Base Model**: ResNet18 (pretrained)
- **Dataset**: CIFAR-10
- **Number of Classes**: 10
- **Input Size**: 32x32 (resized to 224x224)

## Performance
- Test Accuracy: Check evaluation logs

## Classes
{', '.join(class_names)}

## Usage
See HuggingFace documentation for inference examples.
"""

        with open("README.md", "w") as f:
            f.write(config_text)

        upload_folder(
            folder_path=".",
            repo_id=HF_MODEL_REPO,
            repo_type="model",
            ignore_patterns=["*.pyc", "__pycache__", ".git*", "*.ipynb"]
        )
        print(" Model pushed to HF Hub successfully!")
    except Exception as e:
        print(f"  Note: Could not push to HF Hub automatically.")
        print(f"   Error: {e}")
        print(f"   Manual push: huggingface-cli upload {HF_MODEL_REPO} best_model.pt")

print("\n Model training and saving complete!")

# Finalize W&B
wandb.finish()
print(" W&B run finished")

"""## ✓ Training Complete!

**Next Steps:**

1. **Run the evaluation notebook** (`hf_evaluate.ipynb`) to:
   - Test on CIFAR-10 test set
   - Generate confusion matrix
   - Generate class-wise accuracy bar chart
   - Log 20 sample predictions (10 correct + 10 incorrect)

2. **View results in W&B dashboard:**
   - Go to https://wandb.ai and find your project `cifar10-hf`
   - Check training curves (loss, accuracy)
   - View evaluation metrics

3. **Push outputs to GitHub:**
   - Download evaluation images
   - Commit and push to your GitHub repo

4. **Fill exam sheet with:**
   - Overall test accuracy
   - Class-wise accuracy (all 10 classes, especially class 7/horse)
   - Confusion matrix visualization

**Model Location:**
- Local: `best_model.pt` (in Colab storage)
- HuggingFace Hub: `{HF_MODEL_REPO}` (if push succeeded)
"""